// <auto-generated />

using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Esentis.Horudom.Persistence.Migrations
{
    public partial class Addsnormalizedfields : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.RenameColumn(
                name: "LastName",
                table: "Directors",
                newName: "Lastname");

            migrationBuilder.RenameColumn(
                name: "FirstName",
                table: "Directors",
                newName: "Firstname");

            migrationBuilder.RenameColumn(
                name: "LastName",
                table: "Actors",
                newName: "Lastname");

            migrationBuilder.RenameColumn(
                name: "FirstName",
                table: "Actors",
                newName: "Firstname");

            migrationBuilder.AddColumn<string>(
                name: "NormalizedCountry",
                table: "Movies",
                nullable: false,
                defaultValue: "");

            migrationBuilder.AddColumn<string>(
                name: "NormalizedTitle",
                table: "Movies",
                nullable: false,
                defaultValue: "");

            migrationBuilder.AlterColumn<long>(
                name: "DirectorId",
                table: "MovieDirectors",
                nullable: false,
                oldClrType: typeof(int),
                oldType: "integer");

            migrationBuilder.AlterColumn<long>(
                name: "ActorId",
                table: "MovieActors",
                nullable: false,
                oldClrType: typeof(int),
                oldType: "integer");

            migrationBuilder.AlterColumn<long>(
                name: "Id",
                table: "Directors",
                nullable: false,
                oldClrType: typeof(int),
                oldType: "integer")
                .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .OldAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            migrationBuilder.AddColumn<string>(
                name: "NormalizedFirstname",
                table: "Directors",
                nullable: false,
                defaultValue: "");

            migrationBuilder.AddColumn<string>(
                name: "NormalizedLastname",
                table: "Directors",
                nullable: false,
                defaultValue: "");

            migrationBuilder.AlterColumn<long>(
                name: "Id",
                table: "Actors",
                nullable: false,
                oldClrType: typeof(int),
                oldType: "integer")
                .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .OldAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            migrationBuilder.AddColumn<string>(
                name: "NormalizedFirstname",
                table: "Actors",
                nullable: false,
                defaultValue: "");

            migrationBuilder.AddColumn<string>(
                name: "NormalizedLastname",
                table: "Actors",
                nullable: false,
                defaultValue: "");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "NormalizedCountry",
                table: "Movies");

            migrationBuilder.DropColumn(
                name: "NormalizedTitle",
                table: "Movies");

            migrationBuilder.DropColumn(
                name: "NormalizedFirstname",
                table: "Directors");

            migrationBuilder.DropColumn(
                name: "NormalizedLastname",
                table: "Directors");

            migrationBuilder.DropColumn(
                name: "NormalizedFirstname",
                table: "Actors");

            migrationBuilder.DropColumn(
                name: "NormalizedLastname",
                table: "Actors");

            migrationBuilder.RenameColumn(
                name: "Lastname",
                table: "Directors",
                newName: "LastName");

            migrationBuilder.RenameColumn(
                name: "Firstname",
                table: "Directors",
                newName: "FirstName");

            migrationBuilder.RenameColumn(
                name: "Lastname",
                table: "Actors",
                newName: "LastName");

            migrationBuilder.RenameColumn(
                name: "Firstname",
                table: "Actors",
                newName: "FirstName");

            migrationBuilder.AlterColumn<int>(
                name: "DirectorId",
                table: "MovieDirectors",
                type: "integer",
                nullable: false,
                oldClrType: typeof(long));

            migrationBuilder.AlterColumn<int>(
                name: "ActorId",
                table: "MovieActors",
                type: "integer",
                nullable: false,
                oldClrType: typeof(long));

            migrationBuilder.AlterColumn<int>(
                name: "Id",
                table: "Directors",
                type: "integer",
                nullable: false,
                oldClrType: typeof(long))
                .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .OldAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            migrationBuilder.AlterColumn<int>(
                name: "Id",
                table: "Actors",
                type: "integer",
                nullable: false,
                oldClrType: typeof(long))
                .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .OldAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);
        }
    }
}
