//<auto-generated />

using Microsoft.EntityFrameworkCore.Migrations;

namespace Esentis.Horudom.Persistence.Migrations
{
	public partial class Removeslastnamefromactors : Migration
	{
		protected override void Up(MigrationBuilder migrationBuilder)
		{
			migrationBuilder.DropColumn(
				name: "Firstname",
				table: "Actors");

			migrationBuilder.DropColumn(
				name: "Lastname",
				table: "Actors");

			migrationBuilder.DropColumn(
				name: "NormalizedFirstname",
				table: "Actors");

			migrationBuilder.DropColumn(
				name: "NormalizedLastname",
				table: "Actors");

			migrationBuilder.AddColumn<string>(
				name: "Name",
				table: "Actors",
				nullable: false,
				defaultValue: "");

			migrationBuilder.AddColumn<string>(
				name: "NormalizedName",
				table: "Actors",
				nullable: false,
				defaultValue: "");
		}

		protected override void Down(MigrationBuilder migrationBuilder)
		{
			migrationBuilder.DropColumn(
				name: "Name",
				table: "Actors");

			migrationBuilder.DropColumn(
				name: "NormalizedName",
				table: "Actors");

			migrationBuilder.AddColumn<string>(
				name: "Firstname",
				table: "Actors",
				type: "text",
				nullable: false,
				defaultValue: "");

			migrationBuilder.AddColumn<string>(
				name: "Lastname",
				table: "Actors",
				type: "text",
				nullable: false,
				defaultValue: "");

			migrationBuilder.AddColumn<string>(
				name: "NormalizedFirstname",
				table: "Actors",
				type: "text",
				nullable: false,
				defaultValue: "");

			migrationBuilder.AddColumn<string>(
				name: "NormalizedLastname",
				table: "Actors",
				type: "text",
				nullable: false,
				defaultValue: "");
		}
	}
}
